### ISSUE TITLE
HDMI音频

### ISSUE THREAD

**Issue by lugeek** [tianfanfan/deskmini-h470#1]
HDMI插有喇叭的显示器，能切换到显示器的音频输出吗？

**Comment by tianfanfan** [comment]
你描述的状况，我没成功。
我使用的 DP 显示器，以及 蓝牙音响。

这个机型，驱动都还不是很完善。
我也只是寻找了一个通用的配置单以正常使用。

lugeek <notifications@github.com> 于2020年11月30日周一 上午11:08写道：

**Comment by tianfanfan** [comment]
没 HDMI 线。爱莫能助～
